Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Discounts;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Vendors;
using Nop.Core.Infrastructure;
using Nop.Services.Catalog;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Discounts;
using Nop.Services.ExportImport;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Shipping;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class ProductController : BaseAdminController
    {
        #region Fields

        private readonly IAclService _aclService;
        private readonly IBackInStockSubscriptionService _backInStockSubscriptionService;
        private readonly ICategoryService _categoryService;
        private readonly ICopyProductService _copyProductService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ICustomerService _customerService;
        private readonly IDiscountService _discountService;
        private readonly IDownloadService _downloadService;
        private readonly IExportManager _exportManager;
        private readonly IImportManager _importManager;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly IManufacturerService _manufacturerService;
        private readonly INopFileProvider _fileProvider;
        private readonly INotificationService _notificationService;
        private readonly IPdfService _pdfService;
        private readonly IPermissionService _permissionService;
        private readonly IPictureService _pictureService;
        private readonly IProductAttributeParser _productAttributeParser;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IProductAttributeFormatter _productAttributeFormatter;
        private readonly IProductModelFactory _productModelFactory;
        private readonly IProductService _productService;
        private readonly IProductTagService _productTagService;
        private readonly ISettingService _settingService;
        private readonly IShippingService _shippingService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly IStoreContext _storeContext;
        private readonly IUrlRecordService _urlRecordService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IWorkContext _workContext;
        private readonly VendorSettings _vendorSettings;

        #endregion

        #region Ctor

        public ProductController(IAclService aclService,
            IBackInStockSubscriptionService backInStockSubscriptionService,
            ICategoryService categoryService,
            ICopyProductService copyProductService,
            ICustomerActivityService customerActivityService,
            ICustomerService customerService,
            IDiscountService discountService,
            IDownloadService downloadService,
            IExportManager exportManager,
            IImportManager importManager,
            ILanguageService languageService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            IManufacturerService manufacturerService,
            INopFileProvider fileProvider,
            INotificationService notificationService,
            IPdfService pdfService,
            IPermissionService permissionService,
            IPictureService pictureService,
            IProductAttributeParser productAttributeParser,
            IProductAttributeService productAttributeService,
            IProductAttributeFormatter productAttributeFormatter,
            IProductModelFactory productModelFactory,
            IProductService productService,
            IProductTagService productTagService,
            ISettingService settingService,
            IShippingService shippingService,
            IShoppingCartService shoppingCartService,
            ISpecificationAttributeService specificationAttributeService,
            IStoreContext storeContext,
            IUrlRecordService urlRecordService,
            IGenericAttributeService genericAttributeService,
            IWorkContext workContext,
            VendorSettings vendorSettings)
        {
            _aclService = aclService;
            _backInStockSubscriptionService = backInStockSubscriptionService;
            _categoryService = categoryService;
            _copyProductService = copyProductService;
            _customerActivityService = customerActivityService;
            _customerService = customerService;
            _discountService = discountService;
            _downloadService = downloadService;
            _exportManager = exportManager;
            _importManager = importManager;
            _languageService = languageService;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _manufacturerService = manufacturerService;
            _fileProvider = fileProvider;
            _notificationService = notificationService;
            _pdfService = pdfService;
            _permissionService = permissionService;
            _pictureService = pictureService;
            _productAttributeParser = productAttributeParser;
            _productAttributeService = productAttributeService;
            _productAttributeFormatter = productAttributeFormatter;
            _productModelFactory = productModelFactory;
            _productService = productService;
            _productTagService = productTagService;
            _settingService = settingService;
            _shippingService = shippingService;
            _shoppingCartService = shoppingCartService;
            _specificationAttributeService = specificationAttributeService;
            _storeContext = storeContext;
            _urlRecordService = urlRecordService;
            _genericAttributeService = genericAttributeService;
            _workContext = workContext;
            _vendorSettings = vendorSettings;
        }

        #endregion

        #region Utilities

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdateLocalesAsync(Product product, ProductModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(product,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
                await _localizedEntityService.SaveLocalizedValueAsync(product,
                    x => x.ShortDescription,
                    localized.ShortDescription,
                    localized.LanguageId);
                await _localizedEntityService.SaveLocalizedValueAsync(product,
                    x => x.FullDescription,
                    localized.FullDescription,
                    localized.LanguageId);
                await _localizedEntityService.SaveLocalizedValueAsync(product,
                    x => x.MetaKeywords,
                    localized.MetaKeywords,
                    localized.LanguageId);
                await _localizedEntityService.SaveLocalizedValueAsync(product,
                    x => x.MetaDescription,
                    localized.MetaDescription,
                    localized.LanguageId);
                await _localizedEntityService.SaveLocalizedValueAsync(product,
                    x => x.MetaTitle,
                    localized.MetaTitle,
                    localized.LanguageId);

                //search engine name
                var seName = await _urlRecordService.ValidateSeNameAsync(product, localized.SeName, localized.Name, false);
                await _urlRecordService.SaveSlugAsync(product, seName, localized.LanguageId);
            }
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdateLocalesAsync(ProductTag productTag, ProductTagModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(productTag,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);

                var seName = await _urlRecordService.ValidateSeNameAsync(productTag, string.Empty, localized.Name, false);
                await _urlRecordService.SaveSlugAsync(productTag, seName, localized.LanguageId);
            }
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdateLocalesAsync(ProductAttributeMapping pam, ProductAttributeMappingModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(pam,
                    x => x.TextPrompt,

Presentation/Nop.Web/Areas/Admin/Views/Product/Edit.cshtml
@model ProductModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.EditProductDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Products");
}

<form asp-controller="Product" asp-action="Edit" method="post" id="product-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Products.EditProductDetails") - @Model.Name
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Products.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="button" onclick="javascript:OpenWindow('@Url.RouteUrl("Product", new {SeName = Model.SeName})', 800, 600, true); return false;" class="btn btn-info">
                <i class="far fa-eye"></i>
                @T("Admin.Common.Preview")
            </button>
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <button type="button" name="copyproduct" class="btn bg-olive" data-toggle="modal" data-target="#copyproduct-window">
                <i class="far fa-clone"></i>
                @T("Admin.Catalog.Products.Copy")
            </button>
            <span id="product-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="product-delete" />

@if (!Model.IsLoggedInAsVendor)
{
    //product editor settings modal
    @await Html.PartialAsync("_ProductEditorSettingsModal", Model)
}

@*copy product form*@
<div id="copyproduct-window" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="copyproduct-window-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="copyproduct-window-title">@T("Admin.Catalog.Products.Copy")</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>                
            </div>
            <form asp-controller="Product" asp-action="CopyProduct" method="post">
                <div class="form-horizontal">
                    <div class="modal-body">
                        <input asp-for="CopyProductModel.Id" type="hidden" />
                        <div class="form-group row">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.Name" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.Name" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.Published" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.Published" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.CopyImages" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.CopyImages" />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">
                            @T("Admin.Catalog.Products.Copy")
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Presentation/Nop.Web/Areas/Admin/Views/Product/ProductAttributeMappingEdit.cshtml
@model ProductAttributeMappingModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.ProductAttributes.Attributes.EditAttributeDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Products");
}

<form asp-controller="Product" asp-action="ProductAttributeMappingEdit" method="post" id="productattribute-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.EditAttributeDetails")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="Edit" asp-route-id="@Model.ProductId">@T("Admin.Catalog.Products.ProductAttributes.Attributes.BackToProduct")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="productattribute-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductAttributeMappingDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateProductAttributeMapping", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-action="ProductAttributeMappingDelete" asp-button-id="productattribute-delete" />

Presentation/Nop.Web/Areas/Admin/Views/Product/ProductAttributeValueCreatePopup.cshtml
@model ProductAttributeValueModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew").Text;
}
<form asp-controller="Product" asp-action="ProductAttributeValueCreatePopup"
      asp-route-productAttributeMappingId="@Context.Request.Query["productAttributeMappingId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductAttributeValueDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateProductAttributeValue", Model)
</form>

Presentation/Nop.Web/Areas/Admin/Views/Product/TierPriceEditPopup.cshtml
@model TierPriceModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.TierPrices.Edit").Text;
}

    <form asp-controller="Product" asp-action="TierPriceEditPopup"
          asp-route-btnId="@Context.Request.Query["btnId"]"
          asp-route-formId="@Context.Request.Query["formId"]">
        <section class="content">
            <div class="container-fluid">
                <div class="content-header clearfix">
                    <h1 class="float-left">
                        @T("Admin.Catalog.Products.TierPrices.Edit")
                    </h1>
                    <div class="float-right">
                        <button type="submit" name="save" class="btn btn-primary">
                            <i class="far fa-save"></i>
                            @T("Admin.Common.Save")
                        </button>
                        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductTierPriceDetailsButtons, additionalData = Model })
                    </div>
                </div>
                @await Html.PartialAsync("_CreateOrUpdateTierPrice", Model)
                </div>
            </section>
    </form>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.CrossSellsProducts.cshtml
@model ProductModel
<div class="card-body">
    <p>
        @T("Admin.Catalog.Products.CrossSells.Hint")
    </p>
    @if (Model.Id > 0)
    {
    <div class="card card-default">

        <div class="card-body">
            @await Html.PartialAsync("Table", new DataTablesModel
            {
                Name = "crosssellproducts-grid",
                UrlRead = new DataUrl("CrossSellProductList", "Product", new RouteValueDictionary { [nameof(Model.CrossSellProductSearchModel.ProductId)] = Model.CrossSellProductSearchModel.ProductId }),
                UrlDelete = new DataUrl("CrossSellProductDelete", "Product", null),
                Length = Model.CrossSellProductSearchModel.PageSize,
                LengthMenu = Model.CrossSellProductSearchModel.AvailablePageSizes,
                ColumnCollection = new List<ColumnProperty>
                {
                    new ColumnProperty(nameof(CrossSellProductModel.Product2Name))
                    {
                        Title = T("Admin.Catalog.Products.CrossSells.Fields.Product").Text,
                        Render = new RenderCustom("renderColumnCrossSellProductName")
                    },
                    new ColumnProperty(nameof(CrossSellProductModel.Id))
                    {
                        Title = T("Admin.Common.Delete").Text,
                        Width = "100",
                        Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                        ClassName = NopColumnClassDefaults.Button
                    }
                }
            })
            <script>
                function renderColumnCrossSellProductName(data, type, row, meta) {
                    var textRenderer = $.fn.dataTable.render.text().display;
                    return '<a href="@Url.Content("~/Admin/Product/Edit/")' + row.ProductId2 + '">' + textRenderer(row.Product2Name) + '</a>';
                }
            </script>
        </div>
        <div class="card-footer">
            <button type="submit" id="btnAddNewCrossSellProduct" onclick="javascript:OpenWindow('@(Url.Action("CrossSellProductAddPopup", "Product", new {productId = Model.Id, btnId = "btnRefreshCrossSellProducts", formId = "product-form"}))', 800, 800, true); return false;" class="btn btn-primary">
                @T("Admin.Catalog.Products.CrossSells.AddNew")
            </button>
            <button type="submit" id="btnRefreshCrossSellProducts" style="display: none"></button>
            <script>
                $(document).ready(function () {
                    $('#btnRefreshCrossSellProducts').click(function () {
                        //refresh grid
                        updateTable('#crosssellproducts-grid');

                        //return false to don't reload a page
                        return false;
                    });
                });
            </script>
        </div>
    </div>
    }
    else
    {
        <div class="card card-default">
            <div class="card-body">
                @T("Admin.Catalog.Products.CrossSells.SaveBeforeEdit")
            </div>
        </div>
    }
</div>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.GiftCard.cshtml
@model ProductModel

@using Nop.Core.Domain.Catalog;
@using Nop.Services
<script>
    $(document).ready(function() {
        $("#@Html.IdFor(model => model.IsGiftCard)").click(toggleGiftCard);
        toggleGiftCard();
    });


    function toggleGiftCard() {
        if ($('#@Html.IdFor(model => model.IsGiftCard)').is(':checked')) {
            $('#pnlGiftCardType').showElement();
            $('#pnlOverriddenGiftCardAmount').showElement();
        } else {
            $('#pnlGiftCardType').hideElement();
            $('#pnlOverriddenGiftCardAmount').hideElement();
        }
    }
</script>
 <div class="card-body">
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="IsGiftCard" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="IsGiftCard" />
                <span asp-validation-for="IsGiftCard"></span>
            </div>
        </div>
        <nop-nested-setting asp-for="IsGiftCard">
            <div class="form-group row" id="pnlGiftCardType">
                <div class="col-md-3">
                    <nop-label asp-for="GiftCardTypeId" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="GiftCardTypeId" asp-items="@await (((GiftCardType)Model.GiftCardTypeId).ToSelectListAsync())" />
                    <span asp-validation-for="GiftCardTypeId"></span>
                </div>
            </div>
            <div class="form-group row" id="pnlOverriddenGiftCardAmount">
                <div class="col-md-3">
                    <nop-label asp-for="OverriddenGiftCardAmount" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="OverriddenGiftCardAmount" />
                    <span asp-validation-for="OverriddenGiftCardAmount"></span>
                </div>
            </div>
        </nop-nested-setting>
    </div>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdateProductTag.cshtml
@model ProductTagModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}

 <section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="cards-group">
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductTagDetailsTop, additionalData = Model })
                <div class="card card-default card-popup">
                    <div class="card-body">
                        @(await Html.LocalizedEditorAsync<ProductTagModel, ProductTagLocalizedModel>("producttag-localized",
                        @<div>
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <nop-label asp-for="@Model.Locales[item].Name" />
                                </div>
                                <div class="col-sm-9">
                                    <nop-editor asp-for="@Model.Locales[item].Name" />
                                    <span asp-validation-for="@Model.Locales[item].Name"></span>
                                </div>
                            </div>
                            <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
                        </div>
        ,
                        @<div>
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <nop-label asp-for="Name" />
                                </div>
                                <div class="col-sm-9">
                                    <nop-editor asp-for="Name" asp-required="true" />
                                    <span asp-validation-for="Name"></span>
                                </div>
                            </div>
                        </div>
        ))
                    </div>
                </div>
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductTagDetailsBottom, additionalData = Model })
            </div>
        </div>
    </div>
</section>