Presentation/Nop.Web/Areas/Admin/Controllers/ManufacturerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Discounts;
using Nop.Services.Catalog;
using Nop.Services.Customers;
using Nop.Services.Discounts;
using Nop.Services.ExportImport;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Stores;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class ManufacturerController : BaseAdminController
    {
        #region Fields

        private readonly IAclService _aclService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ICustomerService _customerService;
        private readonly IDiscountService _discountService;
        private readonly IExportManager _exportManager;
        private readonly IImportManager _importManager;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly IManufacturerModelFactory _manufacturerModelFactory;
        private readonly IManufacturerService _manufacturerService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IPictureService _pictureService;
        private readonly IProductService _productService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IStoreService _storeService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly IWorkContext _workContext;

        #endregion

        #region Ctor

        public ManufacturerController(IAclService aclService,
            ICustomerActivityService customerActivityService,
            ICustomerService customerService,
            IDiscountService discountService,
            IExportManager exportManager,
            IImportManager importManager,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            IManufacturerModelFactory manufacturerModelFactory,
            IManufacturerService manufacturerService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IPictureService pictureService,
            IProductService productService,
            IStoreMappingService storeMappingService,
            IStoreService storeService,
            IUrlRecordService urlRecordService,
            IWorkContext workContext)
        {
            _aclService = aclService;
            _customerActivityService = customerActivityService;
            _customerService = customerService;
            _discountService = discountService;
            _exportManager = exportManager;
            _importManager = importManager;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _manufacturerModelFactory = manufacturerModelFactory;
            _manufacturerService = manufacturerService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _pictureService = pictureService;
            _productService = productService;
            _storeMappingService = storeMappingService;
            _storeService = storeService;
            _urlRecordService = urlRecordService;
            _workContext = workContext;
        }

        #endregion

        #region Utilities

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdateLocalesAsync(Manufacturer manufacturer, ManufacturerModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(manufacturer,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);

                await _localizedEntityService.SaveLocalizedValueAsync(manufacturer,
                    x => x.Description,
                    localized.Description,
                    localized.LanguageId);

                await _localizedEntityService.SaveLocalizedValueAsync(manufacturer,
                    x => x.MetaKeywords,
                    localized.MetaKeywords,
                    localized.LanguageId);

                await _localizedEntityService.SaveLocalizedValueAsync(manufacturer,
                    x => x.MetaDescription,
                    localized.MetaDescription,
                    localized.LanguageId);

                await _localizedEntityService.SaveLocalizedValueAsync(manufacturer,
                    x => x.MetaTitle,
                    localized.MetaTitle,
                    localized.LanguageId);

                //search engine name
                var seName = await _urlRecordService.ValidateSeNameAsync(manufacturer, localized.SeName, localized.Name, false);
                await _urlRecordService.SaveSlugAsync(manufacturer, seName, localized.LanguageId);
            }
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdatePictureSeoNamesAsync(Manufacturer manufacturer)
        {
            var picture = await _pictureService.GetPictureByIdAsync(manufacturer.PictureId);
            if (picture != null)
                await _pictureService.SetSeoFilenameAsync(picture.Id, await _pictureService.GetPictureSeNameAsync(manufacturer.Name));
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task SaveManufacturerAclAsync(Manufacturer manufacturer, ManufacturerModel model)
        {
            manufacturer.SubjectToAcl = model.SelectedCustomerRoleIds.Any();
            await _manufacturerService.UpdateManufacturerAsync(manufacturer);

            var existingAclRecords = await _aclService.GetAclRecordsAsync(manufacturer);
            var allCustomerRoles = await _customerService.GetAllCustomerRolesAsync(true);
            foreach (var customerRole in allCustomerRoles)
            {
                if (model.SelectedCustomerRoleIds.Contains(customerRole.Id))
                {
                    //new role
                    if (existingAclRecords.Count(acl => acl.CustomerRoleId == customerRole.Id) == 0)
                        await _aclService.InsertAclRecordAsync(manufacturer, customerRole.Id);
                }
                else
                {
                    //remove role
                    var aclRecordToDelete = existingAclRecords.FirstOrDefault(acl => acl.CustomerRoleId == customerRole.Id);
                    if (aclRecordToDelete != null)
                        await _aclService.DeleteAclRecordAsync(aclRecordToDelete);
                }
            }
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task SaveStoreMappingsAsync(Manufacturer manufacturer, ManufacturerModel model)
        {
            manufacturer.LimitedToStores = model.SelectedStoreIds.Any();
            await _manufacturerService.UpdateManufacturerAsync(manufacturer);

            var existingStoreMappings = await _storeMappingService.GetStoreMappingsAsync(manufacturer);
            var allStores = await _storeService.GetAllStoresAsync();
            foreach (var store in allStores)
            {
                if (model.SelectedStoreIds.Contains(store.Id))
                {
                    //new store
                    if (existingStoreMappings.Count(sm => sm.StoreId == store.Id) == 0)
                        await _storeMappingService.InsertStoreMappingAsync(manufacturer, store.Id);
                }
                else
                {
                    //remove store
                    var storeMappingToDelete = existingStoreMappings.FirstOrDefault(sm => sm.StoreId == store.Id);
                    if (storeMappingToDelete != null)
                        await _storeMappingService.DeleteStoreMappingAsync(storeMappingToDelete);
                }
            }
        }

        #endregion

        #region List

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual async Task<IActionResult> List()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageManufacturers))
                return AccessDeniedView();

            //prepare model
            var model = await _manufacturerModelFactory.PrepareManufacturerSearchModelAsync(new ManufacturerSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> List(ManufacturerSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageManufacturers))
                return await AccessDeniedDataTablesJson();

            //prepare model
            var model = await _manufacturerModelFactory.PrepareManufacturerListModelAsync(searchModel);

            return Json(model);
        }

        #endregion

        #region Create / Edit / Delete

        public virtual async Task<IActionResult> Create()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageManufacturers))

Presentation/Nop.Web/Areas/Admin/Views/Manufacturer/Create.cshtml
@model ManufacturerModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Manufacturers.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Manufacturers");
}

<form asp-controller="Manufacturer" asp-action="Create" method="post" id="manufacturer-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Manufacturers.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Manufacturers.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ManufacturerDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

Presentation/Nop.Web/Areas/Admin/Views/Manufacturer/Edit.cshtml
@model ManufacturerModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Manufacturers.EditManufacturerDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Manufacturers");
}

<form asp-controller="Manufacturer" asp-action="Edit" method="post" id="manufacturer-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Manufacturers.EditManufacturerDetails") - @Model.Name
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Manufacturers.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="button" onclick="javascript:OpenWindow('@Url.RouteUrl("Manufacturer", new {SeName = Model.SeName})', 800, 600, true); return false;" class="btn btn-info">
                <i class="far fa-eye"></i>
                @T("Admin.Common.Preview")
            </button>
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="manufacturer-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ManufacturerDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="manufacturer-delete" />

Presentation/Nop.Web/Areas/Admin/Views/Manufacturer/ProductAddPopup.cshtml
@model AddProductToManufacturerSearchModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Manufacturers.Products.AddNew").Text;
}

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}
else
{
    <form asp-controller="Manufacturer" asp-action="ProductAddPopup"
          asp-route-manufacturerId="@Context.Request.Query["manufacturerId"]"
          asp-route-btnId="@Context.Request.Query["btnId"]"
          asp-route-formId="@Context.Request.Query["formId"]">
        <div class="content-header clearfix">
            <h1 class="float-left">
                @T("Admin.Catalog.Manufacturers.Products.AddNew")
            </h1>
            <div class="float-right">
                &nbsp;
            </div>
        </div>

         <section class="content">
            <div class="container-fluid">
                <div class="form-horizontal">
                    <div class="cards-group">
                        <div class="card card-default card-search card-popup">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group row">
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchProductName" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-editor asp-for="SearchProductName" />
                                            </div>
                                        </div>
                                        <div class="form-group row" @(Model.AvailableCategories.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchCategoryId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchCategoryId" asp-items="Model.AvailableCategories" />
                                            </div>
                                        </div>
                                        <div class="form-group row" @(Model.AvailableVendors.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchVendorId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchVendorId" asp-items="Model.AvailableVendors" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group row" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchStoreId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchStoreId" asp-items="Model.AvailableStores" />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchProductTypeId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchProductTypeId" asp-items="Model.AvailableProductTypes" />
                                            </div>
                                        </div>
                                        <div class="form-group row" @(Model.AvailableManufacturers.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                            <div class="col-sm-5">
                                                <nop-label asp-for="SearchManufacturerId" />
                                            </div>
                                            <div class="col-sm-7">
                                                <nop-select asp-for="SearchManufacturerId" asp-items="Model.AvailableManufacturers" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <button type="button" id="search-products" class="btn btn-primary btn-search">
                                            <i class="fas fa-search"></i>
                                            @T("Admin.Common.Search")
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card card-default">
                            <div class="card-body">
                                @await Html.PartialAsync("Table", new DataTablesModel
                                {
                                    Name = "products-grid",
                                    UrlRead = new DataUrl("ProductAddPopupList", "Manufacturer", null),
                                    SearchButtonId = "search-products",
                                    Length = Model.PageSize,
                                    LengthMenu = Model.AvailablePageSizes,
                                    Filters = new List<FilterParameter>
                                    {
                                        new FilterParameter(nameof(Model.SearchProductName)),
                                        new FilterParameter(nameof(Model.SearchCategoryId)),
                                        new FilterParameter(nameof(Model.SearchManufacturerId)),
                                        new FilterParameter(nameof(Model.SearchStoreId)),
                                        new FilterParameter(nameof(Model.SearchVendorId)),
                                        new FilterParameter(nameof(Model.SearchProductTypeId))
                                    },
                                    ColumnCollection = new List<ColumnProperty>
                                    {
                                        new ColumnProperty(nameof(ProductModel.Id))
                                        {
                                            IsMasterCheckBox = true,
                                            Render = new RenderCheckBox(nameof(AddProductToManufacturerModel.SelectedProductIds)),
                                            ClassName =  NopColumnClassDefaults.CenterAll,
                                            Width = "50"
                                        },
                                        new ColumnProperty(nameof(ProductModel.Name))
                                        {
                                            Title = T("Admin.Catalog.Products.Fields.Name").Text
                                        },
                                        new ColumnProperty(nameof(ProductModel.Published))
                                        {
                                            Title = T("Admin.Catalog.Products.Fields.Published").Text,
                                            Width = "100",
                                            ClassName = NopColumnClassDefaults.CenterAll,
                                            Render = new RenderBoolean()
                                        }
                                    }
                                })
                            </div>
                            <div class="card-footer">
                                <button type="submit" name="save" class="btn btn-primary">
                                    <i class="far fa-save"></i>
                                    @T("Admin.Common.Save")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </form>
}

Presentation/Nop.Web/Areas/Admin/Views/Manufacturer/_CreateOrUpdate.Display.cshtml
@model ManufacturerModel

<div class="card-body">
    <div class="form-group row advanced-setting">
        <div class="col-md-3">
            <nop-label asp-for="Published" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="Published" />
            <span asp-validation-for="Published"></span>
        </div>
    </div>
    <div class="form-group row advanced-setting">
        <div class="col-md-3">
            <nop-label asp-for="AllowCustomersToSelectPageSize" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="AllowCustomersToSelectPageSize" />
            <span asp-validation-for="AllowCustomersToSelectPageSize"></span>
        </div>
    </div>
    <nop-nested-setting asp-for="AllowCustomersToSelectPageSize">
        <div id="pnlPageSize" class="form-group row advanced-setting">
            <div class="col-md-3">
                <nop-label asp-for="PageSize" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="PageSize" />
                <span asp-validation-for="PageSize"></span>
            </div>
        </div>
        <div id="pnlPageSizeOptions" class="form-group row advanced-setting">
            <div class="col-md-3">
                <nop-label asp-for="PageSizeOptions" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="PageSizeOptions" />
                <span asp-validation-for="PageSizeOptions"></span>
            </div>
        </div>
    </nop-nested-setting>
    <div class="form-group row advanced-setting">
        <div class="col-md-3">
            <nop-label asp-for="PriceRangeFiltering" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="PriceRangeFiltering" />
            <span asp-validation-for="PriceRangeFiltering"></span>
        </div>
    </div>
    <nop-nested-setting asp-for="PriceRangeFiltering">
        <div class="form-group row advanced-setting" id="pnlManuallyPriceRange">
            <div class="col-md-3">
                <nop-label asp-for="ManuallyPriceRange" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="ManuallyPriceRange" />
                <span asp-validation-for="ManuallyPriceRange"></span>
            </div>
        </div>
        <div id="pnlPriceRange">
            <nop-nested-setting asp-for="ManuallyPriceRange">
                <div class="form-group row advanced-setting">
                    <div class="col-md-3">
                        <nop-label asp-for="PriceFrom" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PriceFrom" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                        <span asp-validation-for="PriceFrom"></span>
                    </div>
                </div>
                <div class="form-group row advanced-setting">
                    <div class="col-md-3">
                        <nop-label asp-for="PriceTo" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PriceTo" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                        <span asp-validation-for="PriceTo"></span>
                    </div>
                </div>
            </nop-nested-setting>
        </div>
    </nop-nested-setting>
    <div class="form-group row">
        <div class="col-md-3">
            <nop-label asp-for="DisplayOrder" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="DisplayOrder" />
            <span asp-validation-for="DisplayOrder"></span>
        </div>
    </div>
    <div class="form-group row" @(Model.AvailableManufacturerTemplates.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
        <div class="col-md-3">
            <nop-label asp-for="ManufacturerTemplateId" />
        </div>
        <div class="col-md-9">
            <nop-select asp-for="ManufacturerTemplateId" asp-items="Model.AvailableManufacturerTemplates" />
            <span asp-validation-for="ManufacturerTemplateId"></span>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#@Html.IdFor(model => model.AllowCustomersToSelectPageSize)").click(togglePageSize);
        $("#@Html.IdFor(model => model.PriceRangeFiltering)").click(togglePriceRangeFiltering);
        $("#@Html.IdFor(model => model.ManuallyPriceRange)").click(togglePriceRangeFiltering);

        togglePageSize();
        togglePriceRangeFiltering();
    });

    function togglePageSize() {
        if ($('#@Html.IdFor(model => model.AllowCustomersToSelectPageSize)').is(':checked')) {
            $('#pnlPageSize').hideElement();
            $('#pnlPageSizeOptions').showElement();
        } else {
            $('#pnlPageSize').showElement();
            $('#pnlPageSizeOptions').hideElement();
        }
    }

    function togglePriceRangeFiltering() {
        if ($('#@Html.IdFor(model => model.PriceRangeFiltering)').is(':checked')) {
            $('#pnlManuallyPriceRange').showElement();

            if ($('#@Html.IdFor(model => model.ManuallyPriceRange)').is(':checked')) {
                $('#pnlPriceRange').showElement();
            } else {
                $('#pnlPriceRange').hideElement();
            }
        } else {
            $('#pnlPriceRange').hideElement();
            $('#pnlManuallyPriceRange').hideElement();
        }
    }
</script>

Presentation/Nop.Web/Areas/Admin/Views/Manufacturer/_CreateOrUpdate.Info.cshtml
@model ManufacturerModel

<div class="card-body">
    @(await Html.LocalizedEditorAsync<ManufacturerModel, ManufacturerLocalizedModel>("manufacturer-name-localized",
    @<div>
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="@Model.Locales[item].Name" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="@Model.Locales[item].Name" />
                <span asp-validation-for="@Model.Locales[item].Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="@Model.Locales[item].Description" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="@Model.Locales[item].Description" asp-template="RichEditor" />
                <span asp-validation-for="@Model.Locales[item].Description"></span>
            </div>
        </div>
        <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
    </div>
,
    @<div>
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="Name" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="Name" asp-required="true" />
                <span asp-validation-for="Name"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="Description" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="Description" asp-template="RichEditor" />
                <span asp-validation-for="Description"></span>
            </div>
        </div>
    </div>))
    
    <div class="form-group row advanced-setting">
        <div class="col-md-3">
            <nop-label asp-for="PictureId" />
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="PictureId" />
            <span asp-validation-for="PictureId"></span>
        </div>
    </div>
</div>